name: Backend
on:
  pull_request:
    paths:
      - "backend/**"
jobs:
  Backend-Actions:
    runs-on: ubuntu-latest     
      steps:
        - name: Check out repository code
        - uses: actions/checkout@v5
        - working-directory: ./backend
        - run: "npm install"
        - run: "npm run test"

