name: Frontend
on:
  pull_request:
    paths:
      - "frontend/**"
jobs:
  Frontend-Actions:
    runs-on: ubuntu-latest
      steps:
          working-directory: ./frontend
        - name: Check out repository code
        - uses: actions/checkout@v5
        - run: "npm install"
        - run: "npm run test"
